baseURL: "https://r4sites.com"
enableRobotsTXT: true
canonifyURLs: true
languageCode: en
title: Create, Publish, and Analyze Personal Websites Using R and RStudio
theme: hargo-hugo-ecommerce-theme
summaryLength: '20'
paginate: 10
disqusShortname: ''
params:
  author: Danny Morris
  contact:
    formAction: 'https://formspree.io/f/xzbydgno'
  copyright: 'Danny Morris 2021'
  currencySymbol: $
  description: Landing page for Create, Publish, and Analyze Personal Websites Using R and RStudio
  email: dmorris10667@gmail.com
  gmapAPI: https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
  googleAnalitycsID: 'UA-196111394-2'
  home: Home
  location: Buffalo, New York
  logo: https://i.imgur.com/x05ydUB.png
  mapLatitude: '51.5223477'
  mapLongitude: '-0.1622023'
  mapMarker: images/marker.png
  mobile: 0124857985320
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: ''
  rating:
    enable: no
    publicKey: 811cf0927332bf51f2e12f84608594ac
    websiteID: '444334'
  snipcartApiKey: ZDVkMDg4MTAtYmM5NC00ZjQyLTlmYTYtMTRmMGZiMmNhOWFmNjM3NTQ3ODkwNTM1MzIwODAw
  social:
    - icon: ti-facebook
      link: '#'
    - icon: ti-twitter-alt
      link: '#'
    - icon: ti-youtube
      link: '#'
    - icon: ti-instagram
      link: '#'
    - icon: ti-pinterest
      link: '#'
menu:
  footer:
    - URL: products/r4sites-book
      name: Download
      weight: 1
    - URL: contact
      name: About the Author
      weight: 2
    - URL: terms-conditions
      name: Terms & Conditions
      weight: 3
  main:
    - URL: products/r4sites-book
      name: Download
      weight: 1
    - URL: contact
      name: About the Author
      weight: 2
    - URL: terms-conditions
      name: Terms & Conditions
      weight: 3
